added gatsby-plugin-offline and deleted newsletter #182
raae/pow-app pull request #221
Opened 2020-12-18 09:44 UTC by olavea

2020-12-21 06:45 UTC, raae requested changes
Also remove the offline plugin, we are not ready for it yet.

2020-12-21 06:45 UTC, raae commented on src/features/onboarding/Welcome.js
> +  const addToHomeScreen = Boolean(parseInt(profile.welcomeCompleted))
To keep with the style rename to `addToHomeScreenCompleted` and then you need to read a new value from profile. I would do `profile.addToHomeScreenCompleted`. You now read `profile.welcomeCompleted` so you will never get the home screen prompt.

2020-12-21 06:45 UTC, raae commented on src/features/onboarding/Welcome.js
> +              welcomeCompleted: "1",
Here again  you need to do `addToHomeScreenCompleted`.

2020-12-21 06:45 UTC, raae commented on src/features/onboarding/Welcome.js
> +  if (welcomeCompleted && addToHomeScreen) return null
If you have renamed as I suggested above, do `addToHomeScreenCompleted`.

2020-12-21 06:45 UTC, raae commented on src/features/onboarding/Welcome.js
> +              add POW! to your home screen
Add a link to `https://www.usepow.app/support/install`

2020-12-22 10:20 UTC, olavea commented
How to add a href hypertext reference? 

I found it in Nick organ's ( @skilldrick ) book Javascript For Kids page 86

2020-12-28 08:27 UTC, olavea commented
<link rel="icon"
        href="data:image/svg+xml,
        <svg xmlns=%22http://w3.org/2000/svg%22 viewBox=%220 0 100 100%22>
        <text y=%22.9em%22 font-size=%2290%22>💩</text>
        </svg>" />

2020-12-28 20:14 UTC, raae commented
Looks good, will have to test properly before accepting.

2021-01-04 10:26 UTC, raae commented on src/features/onboarding/Welcome.js
> +        // Don't do some A2HS magic
You need to do exactly the same as in the welcome case. Do not look at the old newsletter case as I tried to do something smart there that never really worked.

2021-01-05 06:38 UTC, raae requested changes

2021-01-05 06:38 UTC, raae commented on src/features/auth/slice.js
> +    return true
Remove this please

2021-01-05 06:38 UTC, raae commented on src/features/onboarding/Welcome.js
> +  //  const newsletterCompleted = profile.newsletter !== undefined
Remove unused stuff

2021-01-05 06:38 UTC, raae commented on src/features/auth/slice.js
> +    return true
This should not be commited

2021-01-05 06:38 UTC, raae commented on src/features/onboarding/Welcome.js
> +    console.log({name});
Remove

2021-01-11 09:37 UTC, olavea commented
How do I make `addToHomeScreenCompleted: "1"` happen?

2021-04-30 09:50 UTC, closed without merging

2021-05-08 06:39 UTC, olavea commented
Does this mean I am done with this?

2021-05-09 14:39 UTC, raae commented
Not sure, but we'll start over.